---
- hosts: all
  tasks:


  - name: packages | ensure apt list dir exists
    file:
      path: /var/lib/apt/lists/
      state: directory
      mode: 0755

  - name: Update apt cache
    become: yes
    apt:
      update_cache: yes

  - name: Install additional packages
    become: yes
    apt:
      pkg:
        - gpg
        - gpg-agent
        - python3
        - python3-pip
        - ufw
        - vim
        - htop
        - sshpass
    tags:
      - config.packages

  - name: Deny all ingress connections
    community.general.ufw:
      policy: deny
      direction: incoming
    tags:
      - config.firewall

  - name: allow ingress ssh
    community.general.ufw:
      rule: allow
      port: ssh
      proto: tcp
      direction: in
    tags:
      - config.firewall

  - name: allow rpc ingress port
    community.general.ufw:
      rule: allow
      proto: tcp
      direction: in
      port: '8899'
    tags:
      - config.firewall

  - name: deny out from any to 10.0.0.0/8
    community.general.ufw:
      rule: deny
      direction: out
      src: '{{ item }}'
    loop:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
      - 100.64.0.0/10
      - 198.18.0.0/15
      - 169.254.0.0/16
    tags:
      - config.firewall

  - name: Enable ufw
    community.general.ufw:
      state: enabled
    tags:
      - config.firewall

  - name: check is real cpu
    stat:
      path: /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    register: scaling_governor_exists
    tags:
      - config.cpu

  - name: set cpu governor to performance
    shell: echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
    become: yes
    become_user: root
    tags:
      config.cpu
    when: scaling_governor_exists.stat.exists

  - name: check swap file exists
    stat:
      path: "/mnt/swap/swapfile"
    tags:
      - config.swap
    register: swap_file_exists

  - name: Create swap dir mount point
    file:
      path: "/mnt/swap"
      state: directory
      mode: '0755'
    when: not swap_file_exists.stat.exists

  - name: disable current swap
    command: swapoff -a
    tags:
      - config.swap.file.disable
    when: not swap_file_exists.stat.exists

  - name: Create swap file
    command: dd if=/dev/zero of=/mnt/swap/swapfile bs=1G count=200
             creates="/mnt/swap/swapfile"
    tags:
      - config.swap.file.create
    when: not swap_file_exists.stat.exists

  - name: Change swap file permissions
    file: path="/mnt/swap/swapfile"
          owner=root
          group=root
          mode=0600
    tags:
      - config.swap.file.permissions
    when: not swap_file_exists.stat.exists

  - name: Make swap file
    command: "mkswap /mnt/swap/swapfile"
    tags:
      - config.swap.file.mkswap
    when: not swap_file_exists.stat.exists

  - name: Write swap entry in fstab
    mount: name=none
           src=/mnt/swap/swapfile
           fstype=swap
           opts=sw
           passno=0
           dump=0
           state=present
    tags:
    - config.swap.fstab
    when: not swap_file_exists.stat.exists

  - name: Mount swap
    command: "swapon /mnt/swap/swapfile"
    tags:
      - config.swap.file.swapon
    when: not swap_file_exists.stat.exists

  - name: check ramdisk mount point extsts
    stat:
      path: "/mnt/ramdisk"
    register: ramdisk_exists
    tags:
      - config.ramdisk

  - name: create ramdisk mount point
    file:
      path: "/mnt/ramdisk"
      state: directory
      mode: '0755'
    tags:
      - config.ramdisk.directory
    when: not ramdisk_exists.stat.exists

  - name: Write ramdisk entry in fstab
    mount: name=/mnt/ramdisk
           src=tmpfs
           fstype=tmpfs
           opts=nodev,nosuid,noexec,nodiratime,size=200G
           passno=0
           dump=0
           state=mounted
    tags:
      - config.ramdisk.fstab
    when: not ramdisk_exists.stat.exists

